-- Shared platform: roles for the Exact agent. Run once as SECURITYADMIN / SYSADMIN.
-- One role per agent (and per job type) so every query is attributable and the
-- read-only guarantee is enforced by grants, not by instructions.

CREATE DATABASE IF NOT EXISTS PLATFORM;          -- shared by all department agents
CREATE SCHEMA   IF NOT EXISTS PLATFORM.AGENT_OPS;
CREATE SCHEMA   IF NOT EXISTS PLATFORM.INTEGRATION;

CREATE DATABASE IF NOT EXISTS EXACT;              -- already exists (PUBLIC holds today's exports)
CREATE SCHEMA   IF NOT EXISTS EXACT.RAW;
CREATE SCHEMA   IF NOT EXISTS EXACT.CORE;
CREATE SCHEMA   IF NOT EXISTS EXACT.GOVERNANCE;

CREATE ROLE IF NOT EXISTS AGENT_EXACT_LOADER;    -- nightly jobs on the ETL machine
CREATE ROLE IF NOT EXISTS AGENT_EXACT_RO;        -- skills run by Claude

-- Loader: writes RAW, logs its own runs.
GRANT USAGE ON DATABASE EXACT TO ROLE AGENT_EXACT_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA EXACT.RAW TO ROLE AGENT_EXACT_LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA EXACT.RAW TO ROLE AGENT_EXACT_LOADER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA EXACT.RAW TO ROLE AGENT_EXACT_LOADER;

-- Loader also publishes governance versions (loader/sync_governance.py) and owns CORE views.
GRANT USAGE ON SCHEMA EXACT.GOVERNANCE TO ROLE AGENT_EXACT_LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA EXACT.GOVERNANCE TO ROLE AGENT_EXACT_LOADER;

-- Agent: reads CORE and GOVERNANCE, never RAW writes, never EXACT writes.
GRANT USAGE ON DATABASE EXACT TO ROLE AGENT_EXACT_RO;
GRANT USAGE ON SCHEMA EXACT.CORE TO ROLE AGENT_EXACT_RO;
GRANT USAGE ON SCHEMA EXACT.GOVERNANCE TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON ALL VIEWS  IN SCHEMA EXACT.CORE TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EXACT.CORE TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA EXACT.GOVERNANCE TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EXACT.GOVERNANCE TO ROLE AGENT_EXACT_RO;

-- Both: write to the shared logbook (insert only; append-only by design).
GRANT USAGE ON DATABASE PLATFORM TO ROLE AGENT_EXACT_LOADER;
GRANT USAGE ON DATABASE PLATFORM TO ROLE AGENT_EXACT_RO;
GRANT USAGE ON SCHEMA PLATFORM.AGENT_OPS TO ROLE AGENT_EXACT_LOADER;
GRANT USAGE ON SCHEMA PLATFORM.AGENT_OPS TO ROLE AGENT_EXACT_RO;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA PLATFORM.AGENT_OPS TO ROLE AGENT_EXACT_LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA PLATFORM.AGENT_OPS TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA PLATFORM.AGENT_OPS TO ROLE AGENT_EXACT_RO;
GRANT USAGE ON SCHEMA PLATFORM.INTEGRATION TO ROLE AGENT_EXACT_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA PLATFORM.INTEGRATION TO ROLE AGENT_EXACT_RO;

-- Query history for filling AGENT_OPS.QUERIES (nightly job only).
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE AGENT_EXACT_LOADER;

-- Network policy: the nightly jobs run from the ETL machine (decision 11.13); add its IP
-- to the existing allowlist rather than creating a new policy.
