-- EXACT.CORE: clean current-state views for the agent and Power BI.
-- Field names follow the Exact Online REST API. Marked [VERIFY] = check after the first full load.
-- Latest version per record: QUALIFY on LOADED_AT; deleted records removed via RAW.DELETED.

CREATE OR REPLACE VIEW EXACT.CORE.GL_ACCOUNTS AS
SELECT DIVISION, ID AS GL_ACCOUNT_ID,
  PAYLOAD:Code::STRING          AS GL_CODE,
  PAYLOAD:Description::STRING   AS GL_DESCRIPTION,
  PAYLOAD:Type::NUMBER          AS ACCOUNT_TYPE,        -- 110 = revenue (agreed definition), see GOVERNANCE.ACCOUNT_TYPES
  PAYLOAD:BalanceType::STRING   AS BALANCE_TYPE,        -- 'W' = profit & loss, 'B' = balance sheet
  PAYLOAD:BalanceSide::STRING   AS BALANCE_SIDE,
  PAYLOAD:VATCode::STRING       AS DEFAULT_VAT_CODE,
  PAYLOAD:Costcenter::STRING    AS DEFAULT_COST_CENTER,
  PAYLOAD:Costunit::STRING      AS DEFAULT_COST_UNIT,
  PAYLOAD:IsBlocked::BOOLEAN    AS IS_BLOCKED,
  PAYLOAD:Created::TIMESTAMP_NTZ AS CREATED_AT,
  PAYLOAD:Modified::TIMESTAMP_NTZ AS MODIFIED_AT
FROM EXACT.RAW.GL_ACCOUNTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIVISION, ID ORDER BY LOADED_AT DESC) = 1;

CREATE OR REPLACE VIEW EXACT.CORE.TRANSACTION_LINES AS
SELECT t.DIVISION, t.ID AS LINE_ID,
  t.PAYLOAD:EntryID::STRING         AS ENTRY_ID,
  t.PAYLOAD:EntryNumber::NUMBER     AS ENTRY_NUMBER,
  t.PAYLOAD:LineNumber::NUMBER      AS LINE_NUMBER,
  t.PAYLOAD:Date::DATE              AS POSTING_DATE,
  t.PAYLOAD:FinancialYear::NUMBER   AS FIN_YEAR,
  t.PAYLOAD:FinancialPeriod::NUMBER AS FIN_PERIOD,
  t.PAYLOAD:JournalCode::STRING     AS JOURNAL_CODE,
  t.PAYLOAD:Type::NUMBER            AS TRANSACTION_TYPE,   -- [VERIFY] closing-entry type code, see governance/account_types.yml
  t.PAYLOAD:GLAccountCode::STRING   AS GL_CODE,
  t.PAYLOAD:AccountCode::STRING     AS CUSTOMER_CODE,      -- relation number = Striker customer code
  t.PAYLOAD:AmountDC::NUMBER(18,2)  AS AMOUNT_EUR,         -- positive = debit
  t.PAYLOAD:AmountVATFC::NUMBER(18,2) AS VAT_AMOUNT_EUR,   -- transaction currency; = EUR unless foreign-currency postings exist
  t.PAYLOAD:VATCode::STRING         AS VAT_CODE,
  t.PAYLOAD:CostCenter::STRING      AS COST_CENTER,
  t.PAYLOAD:CostUnit::STRING        AS COST_UNIT,
  t.PAYLOAD:InvoiceNumber::NUMBER   AS INVOICE_NUMBER,
  t.PAYLOAD:DueDate::DATE           AS DUE_DATE,
  t.PAYLOAD:Status::NUMBER          AS STATUS,              -- 20 = entered, 50 = processed
  t.PAYLOAD:Description::STRING     AS DESCRIPTION,         -- NULL for wage-cost accounts (loader strips it)
  t.PAYLOAD:Created::TIMESTAMP_NTZ  AS CREATED_AT
FROM EXACT.RAW.TRANSACTION_LINES t
LEFT JOIN (SELECT DISTINCT DIVISION, PAYLOAD:EntityKey::STRING AS ENTITY_KEY FROM EXACT.RAW.DELETED) d
  ON d.DIVISION = t.DIVISION AND d.ENTITY_KEY = t.ID
WHERE d.ENTITY_KEY IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.DIVISION, t.ID ORDER BY t.LOADED_AT DESC) = 1;

-- Agreed revenue definition (GL 8000-series analysis): P&L accounts of revenue type.
CREATE OR REPLACE VIEW EXACT.CORE.REVENUE_LINES AS
SELECT l.*, a.GL_DESCRIPTION, -l.AMOUNT_EUR AS REVENUE_EUR
FROM EXACT.CORE.TRANSACTION_LINES l
JOIN EXACT.CORE.GL_ACCOUNTS a ON a.DIVISION = l.DIVISION AND a.GL_CODE = l.GL_CODE
JOIN EXACT.GOVERNANCE.ACCOUNT_TYPES_CURRENT d ON d.ACCOUNT_TYPE = a.ACCOUNT_TYPE AND d.BALANCE_TYPE = a.BALANCE_TYPE
WHERE d.METRIC_CLASS = 'revenue'
  AND l.TRANSACTION_TYPE NOT IN (SELECT TRY_TO_NUMBER(VALUE::STRING) FROM EXACT.GOVERNANCE.SETTINGS_CURRENT, LATERAL FLATTEN(INPUT => SETTING_VALUE) WHERE SETTING = 'closing_entry_types' AND TRY_TO_NUMBER(VALUE::STRING) IS NOT NULL);

CREATE OR REPLACE VIEW EXACT.CORE.COST_LINES AS
SELECT l.*, a.GL_DESCRIPTION, d.METRIC_CLASS, l.AMOUNT_EUR AS COST_EUR
FROM EXACT.CORE.TRANSACTION_LINES l
JOIN EXACT.CORE.GL_ACCOUNTS a ON a.DIVISION = l.DIVISION AND a.GL_CODE = l.GL_CODE
JOIN EXACT.GOVERNANCE.ACCOUNT_TYPES_CURRENT d ON d.ACCOUNT_TYPE = a.ACCOUNT_TYPE AND d.BALANCE_TYPE = a.BALANCE_TYPE
WHERE d.METRIC_CLASS IN ('cost_of_sales', 'operating_cost', 'wage_cost');

-- Wage cost at account x period only (payroll safeguard, section 7).
CREATE OR REPLACE VIEW EXACT.CORE.WAGE_COST AS
SELECT DIVISION, GL_CODE, FIN_YEAR, FIN_PERIOD, SUM(COST_EUR) AS WAGE_COST_EUR
FROM EXACT.CORE.COST_LINES WHERE METRIC_CLASS = 'wage_cost' GROUP BY 1,2,3,4;

-- Open items from read/financial/ReceivablesList and PayablesList (full refresh each night).
CREATE OR REPLACE VIEW EXACT.CORE.OPEN_RECEIVABLES AS
SELECT DIVISION, ID AS OPEN_ITEM_ID,
  PAYLOAD:AccountCode::STRING   AS CUSTOMER_CODE,
  PAYLOAD:InvoiceNumber::NUMBER AS INVOICE_NUMBER,
  PAYLOAD:InvoiceDate::DATE     AS INVOICE_DATE,
  PAYLOAD:DueDate::DATE         AS DUE_DATE,
  PAYLOAD:Amount::NUMBER(18,2)  AS AMOUNT_OPEN_EUR,
  PAYLOAD:JournalCode::STRING   AS JOURNAL_CODE,
  GREATEST(DATEDIFF(day, PAYLOAD:DueDate::DATE, CURRENT_DATE()), 0) AS DAYS_OVERDUE
FROM EXACT.RAW.RECEIVABLES_LIST
WHERE RUN_ID = (SELECT RUN_ID FROM EXACT.RAW.RECEIVABLES_LIST ORDER BY LOADED_AT DESC LIMIT 1);

CREATE OR REPLACE VIEW EXACT.CORE.OPEN_PAYABLES AS
SELECT DIVISION, ID AS OPEN_ITEM_ID,
  PAYLOAD:AccountCode::STRING   AS SUPPLIER_CODE,
  PAYLOAD:InvoiceNumber::NUMBER AS INVOICE_NUMBER,
  PAYLOAD:InvoiceDate::DATE     AS INVOICE_DATE,
  PAYLOAD:DueDate::DATE         AS DUE_DATE,
  PAYLOAD:Amount::NUMBER(18,2)  AS AMOUNT_OPEN_EUR,
  GREATEST(DATEDIFF(day, PAYLOAD:DueDate::DATE, CURRENT_DATE()), 0) AS DAYS_OVERDUE
FROM EXACT.RAW.PAYABLES_LIST
WHERE RUN_ID = (SELECT RUN_ID FROM EXACT.RAW.PAYABLES_LIST ORDER BY LOADED_AT DESC LIMIT 1);

CREATE OR REPLACE VIEW EXACT.CORE.AGING_BANDS AS
SELECT 'receivable' AS SIDE, DIVISION,
  CASE WHEN DAYS_OVERDUE = 0 THEN 'not due' WHEN DAYS_OVERDUE <= 30 THEN '1-30'
       WHEN DAYS_OVERDUE <= 60 THEN '31-60' WHEN DAYS_OVERDUE <= 90 THEN '61-90' ELSE '90+' END AS BAND,
  COUNT(*) AS ITEMS, SUM(AMOUNT_OPEN_EUR) AS AMOUNT_EUR
FROM EXACT.CORE.OPEN_RECEIVABLES GROUP BY 1,2,3
UNION ALL
SELECT 'payable', DIVISION,
  CASE WHEN DAYS_OVERDUE = 0 THEN 'not due' WHEN DAYS_OVERDUE <= 30 THEN '1-30'
       WHEN DAYS_OVERDUE <= 60 THEN '31-60' WHEN DAYS_OVERDUE <= 90 THEN '61-90' ELSE '90+' END,
  COUNT(*), SUM(AMOUNT_OPEN_EUR)
FROM EXACT.CORE.OPEN_PAYABLES GROUP BY 1,2,3;

-- Relations: codes, roles and terms only. Names and contact details are never loaded;
-- NAME_FP / BANK_FP are HMAC fingerprints (used for duplicate and bank-change detection).
CREATE OR REPLACE VIEW EXACT.CORE.RELATIONS AS
SELECT DIVISION, ID AS RELATION_ID,
  TRIM(PAYLOAD:Code::STRING)          AS CUSTOMER_CODE,
  PAYLOAD:IsSupplier::BOOLEAN         AS IS_SUPPLIER,
  PAYLOAD:Status::STRING = 'C'        AS IS_CUSTOMER,       -- [VERIFY]
  PAYLOAD:PaymentConditionSales::STRING    AS PAYMENT_TERM_CODE,
  PAYLOAD:PaymentConditionPurchase::STRING AS PURCHASE_TERM_CODE,
  PAYLOAD:NAME_FP::STRING             AS NAME_FP,
  PAYLOAD:VAT_FP::STRING              AS VAT_FP,
  PAYLOAD:COC_FP::STRING              AS COC_FP,
  PAYLOAD:Blocked::BOOLEAN            AS IS_BLOCKED,
  PAYLOAD:Created::TIMESTAMP_NTZ      AS CREATED_AT
FROM EXACT.RAW.ACCOUNTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIVISION, ID ORDER BY LOADED_AT DESC) = 1;

-- Supplier bank accounts: fingerprint history only. A new fingerprint for the same relation = change.
CREATE OR REPLACE VIEW EXACT.CORE.SUPPLIER_BANK_CHANGES AS
SELECT DIVISION, PAYLOAD:Account::STRING AS RELATION_ID, PAYLOAD:BANK_FP::STRING AS BANK_FP,
  MIN(LOADED_AT) AS FIRST_SEEN
FROM EXACT.RAW.BANK_ACCOUNTS GROUP BY 1,2,3;

CREATE OR REPLACE VIEW EXACT.CORE.VAT_CODES AS
SELECT DIVISION, ID, PAYLOAD:Code::STRING AS VAT_CODE, PAYLOAD:Description::STRING AS VAT_DESCRIPTION,
  PAYLOAD:Percentage::FLOAT AS PERCENTAGE, PAYLOAD:Type::STRING AS VAT_TYPE, PAYLOAD:IsBlocked::BOOLEAN AS IS_BLOCKED,
  PAYLOAD:GLToPay::STRING AS GL_TO_PAY_ID, PAYLOAD:GLToClaim::STRING AS GL_TO_CLAIM_ID
FROM EXACT.RAW.VAT_CODES
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIVISION, ID ORDER BY LOADED_AT DESC) = 1;

CREATE OR REPLACE VIEW EXACT.CORE.JOURNALS AS
SELECT DIVISION, ID, PAYLOAD:Code::STRING AS JOURNAL_CODE, PAYLOAD:Description::STRING AS JOURNAL_DESCRIPTION,
  PAYLOAD:Type::NUMBER AS JOURNAL_TYPE, PAYLOAD:GLAccount::STRING AS GL_ACCOUNT_ID,
  PAYLOAD:SuspenseGLAccount::STRING AS SUSPENSE_GL_ACCOUNT_ID
FROM EXACT.RAW.JOURNALS
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIVISION, ID ORDER BY LOADED_AT DESC) = 1;

CREATE OR REPLACE VIEW EXACT.CORE.GL_CLASSIFICATION_MAP AS    -- reporting scheme mapping (RGS or accountant's scheme)
SELECT DIVISION, PAYLOAD:GLAccount::STRING AS GL_ACCOUNT_ID, PAYLOAD:Classification::STRING AS CLASSIFICATION_ID,
  PAYLOAD:GLScheme::STRING AS SCHEME_ID
FROM EXACT.RAW.GL_ACCOUNT_CLASSIFICATION_MAPPINGS
QUALIFY ROW_NUMBER() OVER (PARTITION BY DIVISION, ID ORDER BY LOADED_AT DESC) = 1;

-- Usage evidence per GL account (feeds exact-setup-monitor and the ledger clean-up advisor).
CREATE OR REPLACE VIEW EXACT.CORE.GL_USAGE AS
WITH lines AS (
  SELECT l.DIVISION, l.GL_CODE, COUNT(*) AS LINES_EVER, MAX(l.POSTING_DATE) AS LAST_POSTING,
         SUM(l.AMOUNT_EUR) AS BALANCE_EUR
  FROM EXACT.CORE.TRANSACTION_LINES l
  WHERE l.TRANSACTION_TYPE NOT IN (SELECT TRY_TO_NUMBER(VALUE::STRING) FROM EXACT.GOVERNANCE.SETTINGS_CURRENT, LATERAL FLATTEN(INPUT => SETTING_VALUE) WHERE SETTING = 'closing_entry_types' AND TRY_TO_NUMBER(VALUE::STRING) IS NOT NULL)
  GROUP BY 1,2),
refs AS (
  SELECT DIVISION, GL_ACCOUNT_ID, LISTAGG(DISTINCT REF, ', ') AS REFERENCED_BY FROM (
    SELECT DIVISION, GL_TO_PAY_ID AS GL_ACCOUNT_ID, 'vat:' || VAT_CODE AS REF FROM EXACT.CORE.VAT_CODES
    UNION ALL SELECT DIVISION, GL_TO_CLAIM_ID, 'vat:' || VAT_CODE FROM EXACT.CORE.VAT_CODES
    UNION ALL SELECT DIVISION, GL_ACCOUNT_ID, 'journal:' || JOURNAL_CODE FROM EXACT.CORE.JOURNALS
    UNION ALL SELECT DIVISION, SUSPENSE_GL_ACCOUNT_ID, 'journal-suspense:' || JOURNAL_CODE FROM EXACT.CORE.JOURNALS
    -- [PHASE 2] add items, default accounts, recurring entries, budgets once loaded
  ) WHERE GL_ACCOUNT_ID IS NOT NULL GROUP BY 1,2)
SELECT a.DIVISION, a.GL_CODE, a.GL_DESCRIPTION, a.ACCOUNT_TYPE, a.BALANCE_TYPE, a.IS_BLOCKED,
  COALESCE(l.LINES_EVER, 0) AS LINES_EVER, l.LAST_POSTING, COALESCE(l.BALANCE_EUR, 0) AS BALANCE_EUR,
  r.REFERENCED_BY,
  b.GL_CODE IS NOT NULL AS USED_BY_BILLING_INTEGRATION,
  m.CLASSIFICATION_ID IS NOT NULL AS IS_MAPPED
FROM EXACT.CORE.GL_ACCOUNTS a
LEFT JOIN lines l ON l.DIVISION = a.DIVISION AND l.GL_CODE = a.GL_CODE
LEFT JOIN refs  r ON r.DIVISION = a.DIVISION AND r.GL_ACCOUNT_ID = a.GL_ACCOUNT_ID
LEFT JOIN EXACT.GOVERNANCE.BILLING_INTEGRATION_ACCOUNTS b ON b.GL_CODE = a.GL_CODE
LEFT JOIN (SELECT DISTINCT DIVISION, GL_ACCOUNT_ID, CLASSIFICATION_ID FROM EXACT.CORE.GL_CLASSIFICATION_MAP
           WHERE SCHEME_ID = (SELECT SETTING_VALUE::STRING FROM EXACT.GOVERNANCE.SETTINGS_CURRENT WHERE SETTING = 'reporting_scheme_id')) m
  ON m.DIVISION = a.DIVISION AND m.GL_ACCOUNT_ID = a.GL_ACCOUNT_ID;
