-- EXACT.GOVERNANCE: versioned definitions. Source of truth is governance/*.yml in the repo;
-- loader/sync_governance.py writes a new version row on every merged change.

CREATE TABLE IF NOT EXISTS EXACT.GOVERNANCE.ACCOUNT_TYPES (
  ACCOUNT_TYPE NUMBER, BALANCE_TYPE STRING, LABEL STRING, METRIC_CLASS STRING,
  DEFINITION STRING, DICT_VERSION NUMBER, VALID_FROM TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE VIEW EXACT.GOVERNANCE.ACCOUNT_TYPES_CURRENT AS
SELECT * FROM EXACT.GOVERNANCE.ACCOUNT_TYPES
WHERE DICT_VERSION = (SELECT MAX(DICT_VERSION) FROM EXACT.GOVERNANCE.ACCOUNT_TYPES);

CREATE TABLE IF NOT EXISTS EXACT.GOVERNANCE.SETTINGS (
  SETTING STRING, SETTING_VALUE VARIANT, DICT_VERSION NUMBER, VALID_FROM TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE VIEW EXACT.GOVERNANCE.SETTINGS_CURRENT AS
SELECT * FROM EXACT.GOVERNANCE.SETTINGS
WHERE DICT_VERSION = (SELECT MAX(DICT_VERSION) FROM EXACT.GOVERNANCE.SETTINGS);

CREATE TABLE IF NOT EXISTS EXACT.GOVERNANCE.BILLING_INTEGRATION_ACCOUNTS (  -- decision 11.6
  GL_CODE STRING, NOTE STRING, DICT_VERSION NUMBER, VALID_FROM TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EXACT.GOVERNANCE.RULES (   -- mirror of rules/*.yml, for traceability
  RULE_ID STRING, RULE_VERSION NUMBER, MONITOR STRING, OWNER STRING, SEVERITY STRING,
  THRESHOLD VARIANT, SQL_TEXT STRING, VALID_FROM TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
